import os
import socket
print("WINDOWS 10 CLEANUP SCRIPT")
print("Downloaded from https://github.com/Pyroot3r/Win10cleaner")
hostname = socket.gethostname()
print("Running script on: " + hostname)
os.system("dir")
useless_file = input("enter any useless file, enter their name of the file(with Capitalization if there!): ")
os.remove(useless_file)
print("Deleted " + useless_file)
os.system("cd /")
os.system("tree")
os.system("cd /$Recycle.Bin")
os.getcwd()
os.system("dir")
print("This will delete all files from the Recycle Bin which take up space on your computer")
os.system("*.*")
os.system("cd /")
os.system("cd C:/Windows/Temp")
os.system("dir")
print("This will remove all the junk temp files that windows has generated")
os.system("del *.*")
os.system("cd /")
os.system("cd Temp")
print("This will remove all the junk temp files that windows has generated")
os.system("del *.*")
print("Resolving errors")
os.system("cd /")
os.system("sfc /scannow")
